apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: greeter-previews
spec:
  generators:
  - pullRequest:
      github:
        owner: austinrivard
        repo: testkube
        # Labels is used to filter the PRs that you want to target. (optional)
        # labels:
        # - preview
      # if not using webhooks, how many seconds between polling (default 30 mins)
      # requeueAfterSeconds: 1800
  template:
    metadata:
      name: 'greeter-pr-{{number}}'
    spec:
      source:
        repoURL: 'https://github.com/austinrivard/testkube'
        targetRevision: '{{head_sha}}'
        path: argocd/
        kustomize:
          namePrefix: greeter-pr-{{number}}-
          images:
          - 'docker.io/testkube/greeter:{{head_sha}}'
          patches:
          - target:
              kind: Ingress
              name: ingress-greeter-pr-{{number}}
            patch: |-
              - op: replace
                path: spec/rules/0/host
                value: greeter-pr-{{number}}.test
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: testkube